[package]
name = "htop"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version="0.8.4", features=["macros", "ws"] }
serde_json = "1.0.145"
sysinfo = "0.36.1"
tokio = { version = "1.47.1", features = ["full"] }
tracing-subscriber = "0.3.20"
